name: Deploy Weather UI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build Angular
        run: npm run build

      - name: 🔍 Check Docker Hub secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "❌ DOCKER_USERNAME está vazio ou não existe"
            exit 1
          else
            echo "✅ DOCKER_USERNAME está configurado"
          fi

          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ DOCKER_PASSWORD está vazio ou não existe"
            exit 1
          else
            echo "✅ DOCKER_PASSWORD está configurado"
          fi
        
      - name: 🐳 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build Docker image
        run: |
          docker build \
            -t sergiohscl/weather-ui:latest \
            -t sergiohscl/weather-ui:${{ github.sha }} \
            .

      - name: 🚀 Push Docker image
        run: |
          docker push sergiohscl/weather-ui:latest
          docker push sergiohscl/weather-ui:${{ github.sha }}